---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infra
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.0
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
